sudo: false
language: cpp
cache: ccache
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - libboost1.55-all-dev
        - clang-6.0
        - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="osx-g++-8"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="osx-g++-7"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"
before_install:
- eval $MATRIX_EVAL
install:
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true
  ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew install llvm || brew upgrade llvm ;
  fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"
  ; fi
- if [[ "$LABEL" == "osx-g++-8" ]]; then brew install gcc@8 ; fi
- if [[ "$LABEL" == "osx-g++-7" ]]; then brew install gcc@7 ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export BASEDIR=`pwd` ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd $HOME ; fi
- if [[ "$LABEL" == "aarch64" ]]; then wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then mkdir toolchain && cd toolchain ; fi
- if [[ "$LABEL" == "aarch64" ]]; then tar xfv ../gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
  >/dev/null ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then tar zxvf ../../boost_1_55_0.tar.gz >/dev/null
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd boost_1_55_0 ; fi
- if [[ "$LABEL" == "aarch64" ]]; then ./bootstrap.sh ; fi
- if [[ "$LABEL" == "aarch64" ]]; then curl https://raw.githubusercontent.com/plenteum/plenteum/master/scripts/fix_boost_aarch64.sh
  | sh ; fi
- if [[ "$LABEL" == "aarch64" ]]; then ./b2 toolset=gcc-aarch64 --with-system --with-filesystem
  --with-thread --with-date_time --with-chrono --with-regex --with-serialization --with-program_options
  >/dev/null; fi
- if [[ "$LABEL" == "aarch64" ]]; then export CUSTOM_BOOST_ROOT="-DBOOST_ROOT=`pwd`"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export CUSTOM_TOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../scripts/cross-aarch64.cmake"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then export STRIP="$HOME/toolchain/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-strip"
  ; fi
- if [[ "$LABEL" == "aarch64" ]]; then cd $BASEDIR ; fi
script:
- eval $MATRIX_EVAL
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=true .. ${CUSTOM_TOOLCHAIN} ${CUSTOM_BOOST_ROOT}
- make -j2
before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="Plenteumd miner zedwallet wallet-service zedwallet-beta cryptotest"
- "${STRIP} ${TARGETS}"
- rm -rf plenteum-${TRAVIS_TAG}
- mkdir plenteum-${TRAVIS_TAG}
- cp ${TARGETS} plenteum-${TRAVIS_TAG}/
- cp ../../LICENSE plenteum-${TRAVIS_TAG}/
- tar cvfz plenteum-${TRAVIS_TAG}-${LABEL}.tar.gz plenteum-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp plenteum-${TRAVIS_TAG}-${LABEL}.tar.gz builds
deploy:
  provider: releases
  api_key:
    secure: evLH6n9RuHFKC80eC3x8EKXbqd0CpftofhXeeyUg95ccLnkBlZOAGm85vTPFhCTBTku9qUScczbImm+92dFFpC1zCpn9poiIpYrpQRTMJ3FoKPILv39o1QFLPbH0G724x2CPeoACtRiRxV1ASIXU3ywmrd3v8/Uuf4mc14OFHGsvHooMhMLRxUWe58KGIG3lhT0zwREISozH+UlLIu80KePPuWusVcSTsnDky/qU8gsZmiwPpInQQcZ0ikCtc0FHzVoiLx0Mn7eQvugMLEi8xOp40Ig+1HWt5s9hUHoYDX9HEyypYKjjGdLvClGxu2nE1+0358g0NRuIs/34vl11cID0vyu7n44qshhA1IWl1+d8cT1MQv3mAUqkXhbQM01m4wkZiXDuQ9eqiyGjqcdyNP7rdOreX/PFPxv7/SFJZ2yMaBFRaam6m5mxNVWZt/GHYyIwJ/ah2aIQf7s5eOQlA3K56B2r8rcNNnhfKbLQYhSvZD0ww0iGi0oCmrHXvif9wWBJDLciYc78xzAHy7SNt1vasYw6EaKoa5FtVPwP0QLBUhR3puJtVi3Gr5QugrZCoBbHZ8SVa4xhgeGRiILADIAZ2BcWxVmdFlVYcIGk/8LEdrrP2UVrhK8cUgjLgoaZxtY91xsABiEbO33cqqYs3zD8FVKTFiGAw8+8j63Ldfc=
  file: plenteum-${TRAVIS_TAG}-${LABEL}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    draft: true
    condition: "$_DEPLOYABLE = true"
    repo: plenteum/plenteum
